dist: Xenial
language: cpp
compiler: 
  - gcc
os: 
  - linux
addons:
  apt:
    packages:
      - libgtest-dev
script:
  - mkdir -p build
  - cd build
  - cmake ..
  - cmake --build .
  
notificatios:
  email: false
git: 
  depth: 5
branch:
  only:
    - master
    - dev
