dist: xenial
language: cpp

git:
  submodule: true

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - lcov
env:
  - MYCXX="g++-7"

before_script:
  - export CXX=$MYCXX
  - $CXX --version
  - cmake --version 

script:
  - mkdir -p build 
  - cd build
  - cmake .. -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  - ctest

branches:
  only:
    - master
    - dev

after_success:
# Create lcov report
- lcov --capture --directory . --output-file coverage.info
- lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
- lcov --list coverage.info # debug info
# Uploading report to CodeCov
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
