dist: xenial
language: cpp

git:
  submodule: true

os: linux
compiler: 'g++-8'
addons:
  apt:
    source: ['ubuntu-toolchain-r-test']
    packages: ['g++-8']

before_script:
  - export CC="gcc-8" CXX="g++-8"
  - $CXX --version
  - cmake --version 

script:
  - mkdir -p build 
  - cd build
  - cmake .. -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release
  - ctest

branches:
  only:
    - master
    - dev

notificatios:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
