dist: Xenial
language: 
  - cpp
compiler:
  - gcc
os:
  - linux
addons:
  apt:
    packages:
      - libgtest-dev
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
branch:
  only:
    - master
    - dev
