dist: trusty
sudo: required
language: 
  - cpp
compilerj:
  - gcc
os:
  - linux
addons:
  apt:
    packages:
      - gcc-6
      - g++-6
      - cmake
      - libgtest-dev
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
branch:
  only:
    - master
    - dev
